module Gem
  module Guardian
    class ArtifactStore
      @client: untyped

      @cache_dir: untyped

      def initialize: (client: untyped, ?cache_dir: untyped) -> void

      def path_for: (untyped dependency) -> untyped
    end
  end
end
module Gem
  module Guardian
    class ArtifactStore
      def initialize: (client: RubygemsClient, ?cache_dir: String) -> void

      def path_for: (Dependency dependency) -> String
    end
  end
end
