module Gem
  module Guardian
    module Checksum
      def self?.sha256_file: (untyped path) -> untyped
    end
  end
end
module Gem
  module Guardian
    module Checksum
      def self.sha256_file: (String path) -> String
    end
  end
end
