module Gem
  module Guardian
    Dependency: untyped
  end
end
module Gem
  module Guardian
    class Dependency
      attr_reader name: String

      attr_reader version: String

      attr_reader platform: String?

      def gem_filename: () -> String
    end
  end
end
