module Gem
  module Guardian
    Error: untyped

    ChecksumNotFound: untyped

    ArtifactFetchError: untyped

    LockfileError: untyped
  end
end
module Gem
  module Guardian
    class Error < StandardError
    end

    class ChecksumNotFound < Error
    end

    class ArtifactFetchError < Error
    end

    class LockfileError < Error
    end
  end
end
