module Gem
  module Guardian
    class RubygemsClient
      @host: untyped

      @http: untyped

      DEFAULT_HOST: "https://rubygems.org"

      def initialize: (?host: untyped, ?http: untyped) -> void

      def expected_sha256: (untyped dependency) -> untyped

      def download_gem: (untyped dependency, untyped destination) -> untyped

      private

      def get: (untyped path) -> untyped

      def platform_matches?: (untyped remote_platform, untyped wanted_platform) -> untyped

      def blank?: (untyped value) -> untyped
    end
  end
end
module Gem
  module Guardian
    class RubygemsClient
      DEFAULT_HOST: String

      def initialize: (?host: String, ?http: untyped) -> void

      def expected_sha256: (Dependency dependency) -> String

      def download_gem: (Dependency dependency, String destination) -> String

      private

      def get: (String path) -> String

      def platform_matches?: (untyped remote_platform, untyped wanted_platform) -> bool

      def blank?: (untyped value) -> bool
    end
  end
end
